version: '3'
services:
  nodejs-server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    container_name: primeninja-api
    volumes:
       - ./server:/usr/src/app/server
       - /usr/src/app/server/node_modules
  react-ui:
    build:
      context: ./client
    ports:
      - "3000:3000"
    container_name: primeninja-ui
    stdin_open: true
    volumes:
       - ./client:/usr/src/app/client
       - /usr/src/app/client/node_modules
